Check if publications list is up-to-date

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,31 +1,42 @@
 #!/bin/bash
 #
-# Update publications list in index.html using Bibble.
+# Update publications list using Bibble.
 
 # Stop on errors
 set -Eeuo pipefail
 
-# Sanity checks
-if ! grep -q "BEGIN BIBBLE" html/index.html; then
-  echo "Error: can't find 'BEGIN BIBBLE' in html/index.html"
-  exit 1
-fi
-if ! grep -q "END BIBBLE" html/index.html; then
-  echo "Error: can't find 'END BIBBLE' in html/index.html"
+# Parse arguments
+if [ "$#" -eq 0 ]; then
+  INDEXHTML="html/index.html"
+elif [ "$#" -eq 1 ]; then
+  INDEXHTML="$1"
+else
+  echo "Usage: $0 [INDEXHTML]"
   exit 1
 fi
 
-# Print commands
-set -x
+# Sanity checks
+if ! test -e $INDEXHTML; then
+  echo "Error: file does not exist: $INDEXHTML"
+  exit 1
+fi
+if ! grep -q "BEGIN BIBBLE" $INDEXHTML; then
+  echo "Error: can't find 'BEGIN BIBBLE' in $INDEXHTML"
+  exit 1
+fi
+if ! grep -q "END BIBBLE" $INDEXHTML; then
+  echo "Error: can't find 'END BIBBLE' in $INDEXHTML"
+  exit 1
+fi
 
 # Copy everything up to and including "BEGIN BIBBLE"
-sed '/BEGIN BIBBLE/q' html/index.html > html/index.html.tmp
+sed '/BEGIN BIBBLE/q' $INDEXHTML > $INDEXHTML.tmp
 
 # Generate new publications list and insert
-bibble publications_database.bib publications_template.html >> html/index.html.tmp
+bibble publications_database.bib publications_template.html >> $INDEXHTML.tmp
 
 # Copy everything after and including "END BIBBLE"
-sed -ne '/END BIBBLE/,$ p' html/index.html  >> html/index.html.tmp
+sed -ne '/END BIBBLE/,$ p' $INDEXHTML  >> $INDEXHTML.tmp
 
 # Clean up
-mv html/index.html.tmp html/index.html
+mv $INDEXHTML.tmp $INDEXHTML
diff --git a/test b/test
--- a/test
+++ b/test
@@ -4,7 +4,16 @@
 set -Eeuo pipefail
 
 # Make sure publications list is up-to-date
-
+cp html/index.html tmp.html
+./build tmp.html
+if ! diff -q html/index.html tmp.html > /dev/null; then
+  echo "Error: publications list is out-of-date"
+  rm -f tmp.html
+  exit 1
+else
+  echo "Publications list is up-to-date"
+  rm -f tmp.html
+fi
 
 # Make sure copyright year is up-to-date
 COPYYEAR=$(grep -E '&copy; \d+ Andrew DeOrio' html/index.html | grep -Eo '\d+')
